### ISSUE TITLE
Native Auctions Views

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1035]
Covers [this upstream Trello card](https://trello.com/c/FDH2rT7J/241-eigen-auction-sale-page-updates).

----

We're turning the martsy view into native code in prep for live integration. There are lots of small pieces, so let's break it down:

- [x] Auction banner view #974 
  - https://github.com/artsy/eigen/pull/1022
  - https://github.com/artsy/eigen/pull/1023
- [x] Redesigned countdown view #1034 
  - https://github.com/artsy/eigen/pull/1044
- [x] Refine UI & capabilities #971
  - #1059
  - #1069 
  - #1075
- [x] Lot views (list & masonry) #972
  - #1149
  - #1153
  - #1177 
  - #1179
- [x] Parallax-ish scrolling behaviour on banner #973
  - #1088 
- [x] Show registration status of user #975
  - #1097
- [x] ~~Native auction registration flow #997~~ (bumped)
- [x] Sale information #1070 
  - #1128 
  - #1175

**Comment by ashfurrow** [comment]
Thought this was "due" Feb 15 (didn't think it'd take that long) but it's due Feb 1 instead. Bringing in @orta for some assistance. /cc @katarina

**Comment by alloy** [comment]
What does “due” mean? Like, it should be able to go live on Feb 1? Should it be in the store by Feb 1?

**Comment by katarinabatina** [comment]
I had many of these updates slated in our milestone that passed on January 17th, which might not have been a clear way to flag the due date (due date being the day we submit to the store). I figured using milestones were a natural way to mark these due dates but if they are not let me know what system would be preferable.

**Comment by ashfurrow** [comment]
I believe "due" meant "implemented", maybe also tested.

**Comment by katarinabatina** [comment]
Is it fair to ask us to all come around a defined definition of due, perhaps ship (ship being when we submit to the store)? And tie the ship date to our milestone? Put all issues in the milestone that need to be shipped by that date...thoughts?

**Comment by alloy** [comment]
@katarinabatina Agreed, I think “due” should be the date that it can be submitted to the App Store (so developed, and tested).

**Comment by orta** [comment]
:+1:

**Comment by alloy** [comment]
@katarinabatina With that definition, is the “due” date still Feb 1?

**Comment by alloy** [comment]
(@ashfurrow Once this discussion about the due date is completed, maybe summarise it and delete all the comments.)

**Comment by katarinabatina** [comment]
@alloy yes, let's make this due Feb 1

**Comment by ashfurrow** [comment]
Looks like we're tracking this in Trello too: https://trello.com/c/FDH2rT7J/241-eigen-auction-sale-page-updates

I think based on the Slack conversation we had that we were going to track these in Trello (one source of truth). If that makes sense, we should consider closing this issue.

**Comment by katarinabatina** [comment]
@ashfurrow agreed we should close this and use the milestone as a marker for the card in trello.

**Comment by ashfurrow** [comment]
OK, gonna close this then.

**Comment by alloy** [comment]
There needs to be a simple way to traverse these separate tickets up to their high-level requirements. I’m fine with these umbrella overviews moving to Trello cards, but right now (without remembering this ticket) I can’t easily do that, so please state on the top of each ticket that they are part of a Trello card and a link to the card.

**Comment by ashfurrow** [comment]
Yeah, agreed. Some of that is on me, but to be honest I'm a bit tired of playing liaison between Trello and GitHub. The eigen team prefers using GitHub issues, and I personally prefer them to Trello cards as well. If it's OK with @devangt and @acjay I'd like to move to tracking auctions-stuff in GitHub milestones, which we can sync with a Trello card. This'd let the team have maximum visibility into what's going on while requiring the least overhead from me. Sound OK?

**Comment by alloy** [comment]
That’s fine with me. To be clear, I’m fine with the umbrella issue being in Trello or wherever, I just want to easily find it without having to remember anything :)

**Comment by ashfurrow** [comment]
Nope, no one has said tracking her is bad, so I'm re-opening ¯\\_(ツ)_/¯

Will go through and add details from PRs I've done in-between.

**Comment by katarinabatina** [comment]
@ashfurrow @alloy I'm in support of staying in Github

**Comment by devangt** [comment]
Sorry for the delay. @acjay and I just chatted and agree with you @katarinabatina. Since the iOS team has all of their work in GitHub it makes sense to have all issues and tickets in relevant milestones in the eigen repo as you already have!

For each sprint we will have a high level placeholder on Auctions Trello to call out the high level iOS work (but note that will only be a placeholder and most work and progress will happen here in Git). 

The only other thing we will track in Trello are show stoppers that pop up time and again so we can track timely issues to closure in the auction season. 

Note: We are also working on synthesizing the thoughts around the project management workflow given some of our discussions and will call for a quick sync/update by mid week. So stay tuned.

**Comment by ashfurrow** [comment]
👍👍👍👍👍

**Comment by alloy** [comment]
@ashfurrow Cool, thanks :+1: 

@katarinabatina @devangt Great, thanks :+1:

**Comment by ashfurrow** [comment]
#1175 should finish this up, waiting on confirmation from Orta and then we can close this and start design QA :tada:

**Comment by orta** [comment]
Yep, only things we need in for shipping are, analytics + spotlight support

**Comment by orta** [comment]
Closing this,
