### ISSUE TITLE
Lot Navigation

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1084]
- [ ] Jump to live lot button #1111 
- [ ] Lot list #1112
- [ ] Split view controller to organize lot list and artwork overview #1113
- [ ] Investigate sticky cells #1114 

----

Components
![image](https://cloud.githubusercontent.com/assets/6482926/12704430/faf2678c-c828-11e5-9d47-25cb06988308.png)

iPhone specific
![image](https://cloud.githubusercontent.com/assets/6482926/12704433/05ac9ca6-c829-11e5-8ab8-13a9e17455b4.png)

iPad specific
![image](https://cloud.githubusercontent.com/assets/6482926/12704434/0c8ceb0c-c829-11e5-9884-8fe4dd9aeadd.png)

**Comment by katarinabatina** [comment]
asset

live bid icon (white gavel)
1x http://cl.ly/3u251F0o0817
2x http://cl.ly/1k0b3k293Y1P

live bid icon (white gavel, for jump to lot button)
1x http://cl.ly/0I0X0F1Q223G
2x http://cl.ly/1S2H1m312u3o

**Comment by katarinabatina** [comment]
iphone animation 
![image](https://cloud.githubusercontent.com/assets/6482926/12705429/d06b7faa-c83f-11e5-8e37-cdd7445fcec4.png)

mov. http://cl.ly/3p3P3o3F2M2q

**Comment by ashfurrow** [comment]
@katarinabatina Could I ask for clarification on how the lot number, artist name, and price labels are organized out for current lots?

<img width="304" alt="screen shot 2016-04-14 at 4 31 48 pm" src="https://cloud.githubusercontent.com/assets/498212/14542733/7b82cd32-025e-11e6-8434-bdf10a587ae2.png">

The distance between the artist name and the current price is inconsistent between the two. "Damien Hirst" looks like it's in a smaller font, was this intentional?

**Comment by katarinabatina** [comment]
@ashfurrow sorry my mistake, the damien hirst type should be 14px as defined but it was mistakenly set to 12 hence the difference. 

here is more precise vertical spacing: 
![image](https://cloud.githubusercontent.com/assets/6482926/14543881/45a5522e-0264-11e6-8697-f1b2897e3171.png)

**Comment by ashfurrow** [comment]
Cool, thanks for the clarification!

**Comment by katarinabatina** [comment]
👍
