### ISSUE TITLE
WebSocket Networking for Live Integration

### ISSUE THREAD

**Issue by ashfurrow** [artsy/eigen#1110]
- [x] Experiment with [SocketRocket](https://github.com/square/SocketRocket) against the Prediction service locally #1103
- [x] State reconciliation via snapshots #1373 
- [x] State reconciliation via events #1374
- [x] Update current "on the block" item for [Artwork Area](https://github.com/artsy/eigen/issues/1085) #1104
- [x] Update current "on the block" item for [Lot Info Area](https://github.com/artsy/eigen/issues/1084) #1105
- [x] Update current "on the block" item for [Lot Navigation Area](https://github.com/artsy/eigen/issues/1084) (iPhone/iPad) #1106 
- [x] Update UI for [Lot Info](https://github.com/artsy/eigen/issues/1083) for lot currently being viewed by user #1107 
- [x] Update [Bid History](https://github.com/artsy/eigen/issues/1082) for lot currently being viewed by user #1108
- [x] [Place a bid](https://github.com/artsy/eigen/issues/1102) flow for placing bid and displaying results of bid (only instance where we send a WebSocket event and need to wait for a corresponding event) #1109

**Comment by acjay** [comment]
FYI, with https://github.com/artsy/prediction/pull/83, there's a good way to pull an initial snapshot of the auction state. Then, the socket URL is just the root of the prediction server you're running against.

**Comment by alloy** [comment]
Related https://github.com/artsy/prediction/issues/85

**Comment by devangt** [comment]
Waiting on real data.

**Comment by ashfurrow** [comment]
I've spoken when @acjay about a method for getting set up locally, which will let me start wiring up UI to actual events from the websocket API. 

First, I need causality running locally, invoked with `run --debug-auth --in-memory` so that I don't need a signed JWT (I can just specify the "bidder" role, and it'll accept it). Then, I need to run prediction locally as well, and invoke its sync_auction script via `npm run sync-auction :auction-slug`. Importantly, I need a `CAUSALITY_BASE_URL` environment variable that points to `localhost`.

This script is responsible for fetching sale information from gravity and creating a corresponding sale in my local causality instance. At this point, the app running in the iOS simulator can rely on staging metaphysics for static data, and local causality for emitting/receiving websocket events. I can use the local prediction instance to send events that the iOS simulator should receive, and vice versa.

**Comment by acjay** [comment]
Yep, looks good!

**Comment by katarinabatina** [comment]
what's the best proof of having this pass QA? Want to close but am not totally sure.

**Comment by ashfurrow** [comment]
It's an umbrella ticket with individual tickets for individual features, I think we can close.
