### ISSUE TITLE
[Onboarding Update] - Master Issue Development

### ISSUE THREAD

**Issue by mennenia** [artsy/eigen#1364]
The place for all implementation tasks, references to discussions, and so forth.

- [x] Dig around current onboarding code
- [x] Splash screen #1325 
- [x] Personalisation questionnaire #1389 
- [x] Artist / Category search #1390 
- [x] Sign up / login refresh #1324 
- [x] Analytics implementation #1247, final requirements: #1459
- [x] Update push notification pre-prompt #1339
- [ ] Decide what to do about this https://github.com/artsy/eigen/issues/1321#issuecomment-199253014

**Comment by anipetrov** [comment]
New issue for analytics implementation here: https://github.com/artsy/eigen/issues/1459

**Comment by mennenia** [comment]
Thanks @anipetrov!
