### ISSUE TITLE
[Home Personalization] Stories.

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#1419]
Documents:
- [design](https://artsy.wake.io/1085): Layout of rails on mobile.
- [doc](https://docs.google.com/document/d/1QJ5NNK_LqVwomlqIg3MOojtRxgTxg9ky4q6ynfPrrUg): Implementation rules of rails.
## General
- [x] As a user, I only want to see for-sale works on the home page, so that I can focus on adding works to my collection.
  - Notes:
    - The only rail that will show not for-sale works is the ‘Recently Saved’ rail.
- [x] As a user, I never want to see ‘Artists to Follow’ rails back-to-back, so that it’s not too overwhelming and I might gloss over _all_ the ‘Artists to Follow’ suggestions.
  - Notes:
    - There should be a minimum of 2 rails in-between each ‘Artists to Follow: [Category]’ rails.
    - These should be backfilled with the ‘Generic Gene’ rails.
    - Where rails are omitted, the rails below it move up in the list.
- [ ] As a inactive user, I want to be reminded to follow artists, so that I’m reminded to get more engaged.
  - Notes:
    - This is not going to be done for v1.

---
- [x] As a user, I want to be able to refresh the home view’s content, so that I get to see new recommendations and randomly selected works.
- [ ] As a user, I home view’s content to automatically refresh every once in a while, so that I get to see new recommendations and randomly selected works without me having to think about it.
## Misc
- [x] As a user, I want to see a ‘Recommended for You’ rail, so that I discover works that I probably like based on previously shown interests.
  - Notes:
    - Recommendation data will only be available after ~12 hours. So never shown after on-boarding.
    - Needs at least 1 follow/save or 1 inquiry.
- [x] As a gallery follower, I want to see a ‘Works by Galleries you Follow’ rail, so that I discover works from all galleries whose judgement I trust.
  - Notes:
    - Sorted by most recently published.
    - Needs at least 1 gallery follow and 1 for-sale work by that gallery.
    - Shows 20 random works from the 60 most recently published works from all galleries.

---
- [x] As a collector, I want to see a ‘Recently Saved’ rail, so that I remember to buy works that had previously piqued my interest.
  - Notes:
    - Needs at least 1 artwork save.
    - Sorted by most recently saved.
- [x] As a collector, I want to also see not for-sale works in the ‘Recently Saved’ rail, so that following/saving gives me a satisfying feeling and shows me that following/saving more will enrich my experience.
## Theme: Artists
- [x] As an artist follower, I want to see a ‘Works by Artists you Follow’ rail, so that I discover works by artists whose work I like.
  - Notes:
    - Needs at least 1 artist follow.
    - Sorted by most recently published.

---
- [x] As an artist follower, I want to see a ‘Works by [Artist]’ rail for an artist I follow, so that I can discover previously overlooked works by an artist I like.
  - Notes:
    - Needs at least 1 artist follow and 1 for-sale work by that artist.
    - 1 for-sale artwork is enough.
- [x] As an artist follower, I want to see a different ‘Works by [Artist]’ rail on each session, so that I discover more artists’ works.
  - Notes:
    - This means that the shown artists needs to be tracked somewhere.
    - Tracking won't happen till v1, but if any, we only need to care about 2 consecutive for now.
- [x] As an artist follower, I want to see a ‘Works by [Artist]’ rail for an artist I do **not** follow that’s related to the artist that I _do_ follow and is highlighted in the above ‘Works by [Artist]’ rail, so that I can discover other artists that produce works I might like.
  - Notes:
    - Needs the ‘Works by [Artist]’ rail for an artist the user follows to be shown.

---
- [x] As a user, I want to see a ‘Artists to follow: Recommended for You’ rail, so that I can discover artists that I will probably like.
  - Notes:
    - Only present when recommendations are available.
    - Check when recommendations are available?
- [x] As a user, I want to see a ‘Artists to follow: Trending’ rail, so that I can discover artists that others in the art world are liking.
  - Notes:
    - Always shown.
    - This is a list of artists curated by Artsy, it’s not really tailored to the specific user.
- [x] As a user, I want to see a ‘Artists to follow: Iconic’ rail, so that I feel like Artsy is the right place to look for distinguished art.
  - Notes:
    - Always shown.
    - This list is based on the top inquired artists on Artsy.
    - Only artists will be shown that have multiple works in museums.
    - Street art will be blocked, as it does not contribute to that distinguished feeling we’re after.
- [ ] As an artist follower, I want ‘Artists to follow: [type]’ rails to be replenished with new suggestions related to the ones I decide to follow, so that I can follow more artist like the ones I just followed.
  - Notes:
    - Artists that you decide to follow should be removed from the list.
    - To ensure smooth scrolling, we should preload a fair amount of artists.
  - Qs:
    - How will followed artists be removed from the list?
    - How will new suggestions be added to the list in a way that makes it clear to the user that new suggestion have been added?
    - How will we signal to the user that the new suggestions are based on the ones they decided to follow?
    - To tackle all of the above, how about we don’t append new suggestions at the end, but replace the ones that were followed with the new suggestions in-place?
## Theme: Genes
- [ ] As a gene follower without a budget, I want to see a ’[Gene]’ rail, so that I discover newly published works in genes that I like.
  - Notes:
    - When a user doesn’t follow a gene, do we infer from artist follows?
- [x] As a gene follower with a budget, I want to see a ’[Gene] Under $[budget]’ rail, so that I can discover newly published works I can afford in genes that I like.
  - Notes:
    - Sort works by most recently published.
    - How are multiple rails shown, underneath each other.
    - Cap at 10 gene rails, from most recently followed.

---
- [x] As a user, I want to see various ‘Generic Gene’ rails, so that I can discover newly published works that I can afford in popular genes.
  - Notes:
    - Always shown.
    - Popularity is based on number of inquiries but also curation by Artsy (collector team) based on what's popular in the art-world at large.
    - Unlike with the ’[Gene] Under $[budget]’ rail, these rails do not show the budget in their titles.
    - Only shows works in the user’s budget if specified, otherwise default to budget buckets shown next to the gene.
    - Genes:
      - Geometric
      - Landscape
      - Emerging Painters Under $10,000
      - Emerging Photographers Under $10,000
      - Street Art Under $5,000
      - Pop Prints & Multiples Under $5,000
      - Black & White Photography
      - Abstract Painting Under $10,000
      - Figurative Painting Under $10,000
      - Collage Works on Paper Under $5,000
  - Qs:
    - What’s the difference between the genes that include a budget and the ones that don’t?
## Events
- [x] As a collector, I want to see a ‘At Auction: [Auction]’ rail for each ongoing auction, so that I don’t miss out on works that are on sale right now.
  - Notes:
    - Requires at least 1 ongoing auction to be available.
- [ ] As a collector, I want to see ‘At Auction: [Auction]’ rails for auctions that are about to close before others, so that I don’t miss out on the opportunity to participate in all auctions.
- [x] As a collector, I want to see a ‘Art Fair Picks for You: [Fair]’ rail for each ongoing fair, so that I see works by Artsy’s partners that are brand new and available now.
  - Notes:
    - Only show inquireable works of our subscribing partners.
    - Will not actually be personalized for v1.
    - Shows 20 random works from the 60 most recently published works from all partners.
    - Unlike web, we show **all** ongoing fairs.
    - Sort auction rails by tier.

**Comment by alloy** [comment]
@mzikherman @cavvia @broskoski @katarinabatina Added a question about personalized genes:

> When a user doesn’t follow a gene, do we infer from artist follows?

**Comment by alloy** [comment]
@katarinabatina @mzikherman Is there a reason why we don’t show galleries near your physical location right now? (Or somewhere in the future?)

**Comment by alloy** [comment]
@katarinabatina Will we add galleries you follow to ‘YOU’ in the future?

**Comment by alloy** [comment]
@katarinabatina Regarding multiple auctions/fairs rails, do we show those immediately underneath each other or do they need to be staggered like the artists rails and, if so, what are the rules?

**Comment by alloy** [comment]
@katarinabatina What will rails look like when we know which ones to show but still need to load the content? Will we show spinners all over the place (ugh) or grey-out the rail?

**Comment by katarinabatina** [comment]
All good questions @alloy 

Q: When a user doesn’t follow a gene, do we infer from artist follows?
A: Not that I know of although it is an interesting idea. 

Q: Is there a reason why we don’t show galleries near your physical location right now?
A: We've been thinking about this for the future, where we can show people works by galleries near by, or popular with collectors near you. Defining what we mean by near is a bit tricky because for users who don't live in major art hubs, we probably won't be able to provide an awesome experience. It might be interesting for a user to be able to follow a "city" or "region" so that those who are interested in what's happening in New York or Berlin but don't necessarily live in those places can get a sense for the "scene." Ultimately I think location will be a lot more relevant when we look towards working on a proper shows app. 

Q:  Will we add galleries you follow to ‘YOU’ in the future?
A: Yes

Q: Regarding multiple auctions/fairs rails, do we show those immediately underneath each other or do they need to be staggered like the artists rails and, if so, what are the rules?
A: No need to stagger they can show one right after another, auctions grouped together, and art fairs grouped together. 

Q: What will rails look like when we know which ones to show but still need to load the content? Will we show spinners all over the place (ugh) or grey-out the rail?
A: Good one...let me have a think about what we can do. I do think what the web is doing with the "dummy" artworks rails in gray is a nice touch, perhaps we can do something similar.

**Comment by mennenia** [comment]
FYI, there is discussion going on about artist rail data [over here on metaphysics](https://github.com/artsy/metaphysics/issues/360).

**Comment by katarinabatina** [comment]
@joeyAghion is there anyway for me to test my results? To see what this api would generate for me?

**Comment by alloy** [comment]
Even though we haven’t done everything yet, I’m going to close this for now.
