### ISSUE TITLE
[iOS 9] Add ‘App Search’ support

### ISSUE THREAD

**Issue by alloy** [artsy/eigen#777]
This makes it so that users can find Artsy content, provided by the app, in Spotlight (ie. the search bar on the home screen) and in Safari search results. People interested in art and thus searching for keywords in Safari will then also get Artsy content suggested instead of them going off to Google search results.

https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/index.html#//apple_ref/doc/uid/TP40016308

From reading the full App Search guide, it’s clear that we really have to support all the various components to get the best search results, as pointed out by @jessekedy in the “Enhance the Experience” section (see comment below).

----

Activities/Navigation:
- [x] #781: When the user views an entity such as an artwork, artist, gene, fair, auction, etc, we should create a `NSUserActivity` object that’s publicly searchable, to indicate engagement with that particular entity content. Be sure to set the `webpageURL` to the URL of the content on Force so that the search result gets properly counted for in Apple’s ranking system. (See [this](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1) doc.)
- [x] #782: Add and remove favourites (artwork, artists, genes) to the on-device index with the Core Spotlight framework. Be sure to set the `uniqueIdentifier` and `relatedUniqueIdentifier` to the URL of the content on Force so that the search result gets properly counted for in Apple’s ranking system. (See [this](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/AppContent.html#//apple_ref/doc/uid/TP40016308-CH7-SW1) doc.)
- [x] #768: Implement Handoff so that when the user taps search results from the above indexes the user is taken to the relevant content in the app.
  - [x] Native (Eigen) to web (desktop browser).
  - [x]  Web (desktop browser) to native (Eigen).

Web Content:
- [x] #767: Add support for Universal Links to Eigen.
- [x] Ensure Apple can discover our content by specifying the artsy.net URL as our support or marketing website in the App Store metadata.
- [x] https://github.com/artsy/force/issues/3388: Force/Martsy will have to allow the `Applebot` to crawl our site by amending the `robots.txt` file.
- Force/Martsy will have to specify deep links for each entity’s content by either specifying it as part of the Smart App Banner, Twitter Cards, or App Links metadata.
  - [x] https://github.com/artsy/force/issues/3389
  - [x] https://github.com/artsy/microgravity/issues/1046
- [x] https://github.com/artsy/force/issues/3390: Force~~/Martsy~~ should enrich search results by providing metadata as specified by [schema.org](http://schema.org) and [Open Graph](http://ogp.me) metadata to specify title, description, and image data for the search results.
- [x] Force/Martsy should be inspected as being properly discoverable with the [App Search API Validation Tool](https://search.developer.apple.com/appsearch-validation-tool). (Part of the above tickets.)
- [ ] Force/Martsy should load content as fast as possible, as this also affects search result ranking. See e.g. https://github.com/artsy/force/issues/3338, https://github.com/artsy/microgravity/issues/871, and https://github.com/artsy/microgravity/issues/1040.

**Comment by alloy** [comment]
From @jessekedy:

> I realize this is a many-headed beast that involves cross-team ko-lab-o-ration, and that some of this work may have already been done. Since the upside for Artsy could be pretty significant, I was hoping to get a sense of -
> * who's managing the project (assuming @katarinabatina & @anipetrov)
> * who's already done what / who owns which remaining tasks / whether the artsy.net team is looped in
> * how Growth can support this
>
> Below are the high level to-do's from the App Search Programming Guide (prerelease). Feel free to respond in-line below, or point to existing GH issues or Trello cards.

### Search Fundamentals

Search in iOS 9 gives people great ways to access information inside of your app, even when it isn’t installed. When you make your content searchable, users can access activities and content deep within your app through Spotlight and Safari search results, Handoff, Siri Suggestions, and Reminders. Making your content searchable helps you enhance the user experience of your app and improve its discoverability.

### Make Items Searchable
* [Index Activities and Navigation Points](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1)  
  The NSUserActivity class provides methods that let you capture specific app states and navigation points that the user has previously visited and then restore them later using Handoff...
* [Index App Content](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/AppContent.html#//apple_ref/doc/uid/TP40016308-CH7-SW1)  
  ...When you use Core Spotlight APIs to make items searchable, you make it easy for users to find their content in Spotlight search results.
* [Mark Up Web Content](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1)  
  ...Using web markup lets the Applebot web crawler index your content in Apple’s server-side index, which makes it available to all iOS users in Spotlight and Safari search results.
* [Support Universal Links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW1)  
  When you support universal links, iOS 9 users can tap a link to your website and get seamlessly redirected to your installed app without going through Safari. If your app isn’t installed, tapping a link to your website opens your website in Safari.

### Enhance the Experience
* [Combine APIs to Increase Coverage](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/CombiningAPIs.html#//apple_ref/doc/uid/TP40016308-CH10-SW1)  
  ...In your app, using multiple APIs often means that you index the same content in more than one way. On these occasions, it's crucial that you relate the various representations of a single item so that you can avoid giving users duplicate items in search results. Avoiding duplication can also help improve the ranking of your items.
* [Improve the Ranking of Your Results](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/SearchUserExperience.html#//apple_ref/doc/uid/TP40016308-CH11-SW1)  
  iOS 9 users expect app search to give them the most relevant results, regardless of where the content comes from. To deliver the best user experience, iOS determines the quality and ranking of a searchable item by measuring:
  - The frequency with which users view your content (which is captured when you use NSUserActivity)
  - The amount of engagement users have with your content (determined by the engagement ratio, which is based on the number of times users tap an item related to your app and the number of app-related items that are displayed in search results)
  - The popularity of a URL in your website and the amount of structured data available

**Comment by alloy** [comment]
After reading the full App Search guide, it’s clear that we really have to support **all** the various components to get the best search results, as pointed out by @jessekedy in the “Enhance the Experience” section.

**Comment by alloy** [comment]
Activities/Navigation:
* When the user views an entity such as an artwork, artist, gene, fair, auction, etc, we should create a `NSUserActivity` object that’s publicly searchable, to indicate engagement with that particular entity content. Be sure to set the `webpageURL` to the URL of the content on Force so that the search result gets properly counted for in Apple’s ranking system. (See [this](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/Activities.html#//apple_ref/doc/uid/TP40016308-CH6-SW1) doc.)
* Add and remove favourites (artwork, artists, genes) to the on-device index with the Core Spotlight framework. Be sure to set the `uniqueIdentifier` and `relatedUniqueIdentifier` to the URL of the content on Force so that the search result gets properly counted for in Apple’s ranking system. (See [this](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/AppContent.html#//apple_ref/doc/uid/TP40016308-CH7-SW1) doc.)
* Implement Handoff so that when the user taps search results from the above indexes the user is taken to the relevant content in the app. See #768.

Web Content:
* Add support for Universal Links to Eigen. See #767.
* Ensure Apple can discover our content by specifying the artsy.net URL as our support or marketing website in the App Store metadata.
* Force/Martsy will have to allow the `Applebot` to crawl our site by amending the `robots.txt` file.
* Force/Martsy will have to specify deep links for each entity’s content by either specifying it as part of the Smart App Banner, Twitter Cards, or App Links metadata.
* Force/Martsy should enrich search results by providing metadata as specified by [schema.org](http://schema.org) and [Open Graph](http://ogp.me) metadata to specify title, description, and image data for the search results.
* Force/Martsy should be inspected as being properly discoverable with the [App Search API Validation Tool](https://search.developer.apple.com/appsearch-validation-tool).
* Force/Martsy should load content as fast as possible, as this also affects search result ranking. See e.g. https://github.com/artsy/microgravity/issues/871 & https://github.com/artsy/microgravity/issues/1040.

**Comment by alloy** [comment]
An example of the validation tool for [this artwork](https://www.artsy.net/artwork/andy-warhol-myths-portfolio-dracula-f-and-sii-dot-264-1981-1):

<img width="1182" alt="screen shot 2015-09-08 at 21 13 12" src="https://cloud.githubusercontent.com/assets/2320/9744902/d66491aa-566e-11e5-806c-70e7765b47ef.png">

**Comment by alloy** [comment]
Tomorrow I will split these items off into individual issues on Eigen and Force/Martsy.

**Comment by alloy** [comment]
@craigspaeth The items relavent to Force/Martsy are basically all from [this guide](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/WebContent.html#//apple_ref/doc/uid/TP40016308-CH8-SW1).

**Comment by alloy** [comment]
Regarding providing thumbnail metadata that’s to be shown in the enriched search results:

> The optimal size for a thumbnail image varies, depending on the iOS device displaying the search result. If you are indexing the same sized image on all devices, it’s recommended that you use an image with a minimum size of 180 x 270 pixels. Here are some examples of appropriate image sizes:
>
> * For a square or circular image, use 180 x 180 pixels.
> * For an image that is taller than it is wide, use a height of 270 pixels and let the width be determined by maintaining the original aspect ratio. In this case, the image is center-aligned.
> * For an image that is wider than it is tall, use a width of 180 pixels and let the height be determined by maintaing the original aspect ratio. In this case, the image is top-aligned.
>
> If you want to take the current device into account when indexing an image, you can optimize the size to index smaller images in the following ways:
>
> * On iPhone 5s and earlier models, use an image that has a minimum width of 40 pixels or a minimum height of 60 pixels.
> * On iPhone 6 and all iPad models, use an image that has a minimum width of 120 pixels or a minimum height of 180 pixels.
> * On iPhone 6 Plus, use an image that has a minimum width of 180 pixels or a minimum height of 270 pixels.

**Comment by alloy** [comment]
@orta I’m thinking there might be some potential for generating `NSUserActivity` objects from our existing `ARAnalytics` usage, but will have to sleep on that a bit. For instance, an activity object wants metadata that you would normally never send to an analytics provider, e.g. the actual full content vs just an identifier.

**Comment by orta** [comment]
We could create our own [ARAnalyticalProvider](https://github.com/orta/ARAnalytics/blob/master/ARAnalyticalProvider.h) subclass that is based on doing NSActivity - the bit that is odd is that we will need to use different names specific to that.

**Comment by alloy** [comment]
> Force/Martsy should load content as fast as possible, as this also affects search result ranking. See e.g. https://github.com/artsy/microgravity/issues/871 & https://github.com/artsy/microgravity/issues/1040.

@craigspaeth Do you think I should file a ticket for this on Force and maybe improve the Martsy one?

**Comment by alloy** [comment]
FYI I’ve cleanup this thread, so it might not completely reflect your notification emails anymore.

**Comment by alloy** [comment]
Waiting for feedback from Apple/forums on whether Applebot is able to correctly crawl our site and on https://forums.developer.apple.com/message/67381. However, I’m considering this done, especially because any changes needed resulting from that feedback would be on martsy, which can be deployed at any time and thus doesn’t hold up our release.

**Comment by alloy** [comment]
@craigspaeth Thanks for all the support and work on the web end!

![](http://media1.giphy.com/media/HX3lSnGXZnaWk/giphy.gif)
